### ISSUE TITLE
Minimal expressjs sample?

### ISSUE THREAD

**Issue by retorquere** [kndt84/passport-cognito#6]
I'm trying to put together a minimal sample but I'm not sure how the passport-cognito is supposed to go. Apologies in advance, I'm used to Auth0 which have spoiled me with fully-working starter code. Do you know of any sample code that uses passport-cognito?

**Comment by kndt84** [comment]
I will add passport-cognito example, but it takes some time. 

The following link would be a good example to understand how to use express and passport. Instead of using passport-facebook strategy, try to use passport-cognito one. 
https://github.com/passport/express-4.x-facebook-example/blob/master/server.js

**Comment by retorquere** [comment]
Hi, thanks for the feedback. I'm superficially familiar with expressjs/passport; I have a functioning express/passport/auth0 stack, but going by the sample in the README, I don't know what I should do in

```
process.nextTick(function() {
      ...
      cb(null, user);
    });
```

and the facebook example doesn't have the 

```
$.ajax({
  type: "POST",
  url: '/auth/cognito',
  data: { username: username, password: password }
})
```

part.

**Comment by kndt84** [comment]
This code is browser side one for sending POST request to Node.js server.
`
$.ajax({
  type: "POST",
  url: '/auth/cognito',
  data: { username: username, password: password }
})
`
